const lengths = {
  MIN_PASSWORD_LENGTH: 8,
  MAX_PASSWORD_LENGTH: 128,
  MIN_NAME_LENGTH: 1,
  MAX_NAME_LENGTH: 30,
  MAX_COMMENT_LENGTH: 500,
  MAX_PROMO_CODE_LENGTH: 10,
  MAX_GUESTS: 50,
};

const DEFAULT_PHONE_COUNTRY = "UA";

module.exports = {
  lengths,
  DEFAULT_PHONE_COUNTRY,
};
